### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by sandy-huang** [robertgallup/bmp2hex#4]
hjc@hjc-PC:~/disk-2/tool/bmp2hex/python-bmp2hex$ python bmp2hex.py -w 32 320x240.bmp 
PROGMEM const struct {
  unsigned int   width;
  unsigned int   height;
  unsigned int   bitDepth;
  uint8_t *pixel_data[230400];
} 320X240 = {
320, 240, 24, {

}
};
Traceback (most recent call last):
  File "bmp2hex.py", line 248, in <module>
    if __name__ == '__main__': main()
  File "bmp2hex.py", line 106, in main
    bmp2hex(f.name, tablewidth, sizebytes, invert, raw, named, double, xbm)
  File "bmp2hex.py", line 226, in bmp2hex
    v = values[ndx] ^ invertbyte
IndexError: list index out of range

**Comment by robertgallup** [comment]
Thanks for reporting this! So, I just tried creating a 320x240 RGB bmp and testing it out. It seems to work OK for me (it always works just fine for the developer! :) ).

I think the issue you may be having is that an RGB .bmp file must be in 5:6:5 (16-bit) format. The "24" as the bitDepth value in the output structure suggests the .bmp may not be in that format (bit depth should be "16"). Photoshop and GIMP image editors can both output this format, though it takes a little digging to select the correct options.

**Comment by robertgallup** [comment]
I just released a small update that does a better job of reporting unsupported files.
